#!/usr/bin/env python3
"""Send a packed firmware image to the bootloader serial IAP receiver."""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path


SYNC = b"BOTA"
CHUNK_SIZE = 128
HEADER_SIZE = 40
CTRL_READY_IMAGE = 0x11
CTRL_ACK = 0x06
CTRL_NACK = 0x15
FAIL_MARKERS = (
    "fail",
    "bad",
    "timeout",
    "rejected",
)


def drain_serial(ser) -> bool:
    """Print any text currently available from the bootloader."""
    printed = False

    while True:
        data = ser.read(ser.in_waiting or 1)
        if not data:
            break

        print(data.decode(errors="replace"), end="", flush=True)
        printed = True

    return printed


def wait_for_control(ser, expected: int, timeout: float) -> bool:
    """Print bootloader logs until the expected control byte arrives."""
    end_time = time.monotonic() + timeout
    text_buffer = ""

    while time.monotonic() < end_time:
        data = ser.read(1)
        if data:
            for byte in data:
                if byte == expected:
                    return True

                if byte == CTRL_NACK:
                    print("[PC] got NACK")
                    return False

                text = bytes((byte,)).decode(errors="replace")
                print(text, end="", flush=True)
                text_buffer = (text_buffer + text)[-4096:]

                lowered = text_buffer.lower()
                if any(fail_marker in lowered for fail_marker in FAIL_MARKERS):
                    return False
        else:
            time.sleep(0.02)

    return False


def main() -> None:
    parser = argparse.ArgumentParser(description="Send firmware package through USART IAP.")
    parser.add_argument("package", type=Path, help="package generated by firmware_pack.py")
    parser.add_argument("--port", required=True, help="serial port, for example COM5")
    parser.add_argument("--baud", type=int, default=115200)
    parser.add_argument("--delay", type=float, default=0.005, help="delay between chunks")
    parser.add_argument("--post-listen", type=float, default=5.0, help="seconds to keep reading logs after send")
    parser.add_argument("--read-timeout", type=float, default=0.03, help="serial read timeout while draining logs")
    parser.add_argument("--ready-timeout", type=float, default=10.0, help="seconds to wait for READY_IMAGE control byte")
    parser.add_argument("--ack-timeout", type=float, default=10.0, help="seconds to wait for each ACK control byte")
    args = parser.parse_args()

    try:
        import serial
    except ImportError:
        print("pyserial is required: python -m pip install pyserial", file=sys.stderr)
        raise

    data = args.package.read_bytes()
    if len(data) < HEADER_SIZE:
        raise ValueError(f"package is too small: {len(data)} bytes")

    header = data[:HEADER_SIZE]
    image = data[HEADER_SIZE:]

    with serial.Serial(args.port, args.baud, timeout=args.read_timeout) as ser:
        print(f"[PC] Open {args.port} @ {args.baud}")
        drain_serial(ser)

        print("[PC] Send 'U' to enter IAP window...")
        ser.write(b"U")
        time.sleep(0.2)
        drain_serial(ser)

        print("[PC] Send BOTA sync...")
        ser.write(SYNC)
        ser.flush()
        time.sleep(args.delay)
        drain_serial(ser)

        print(f"[PC] Send header ({len(header)} bytes)...")
        ser.write(header)
        ser.flush()

        print("[PC] Wait for READY_IMAGE...")
        if not wait_for_control(ser, CTRL_READY_IMAGE, args.ready_timeout):
            print("[PC] Bootloader did not become ready for image data.")
            return
        print("[PC] got READY_IMAGE")

        print(f"[PC] Send image ({len(image)} bytes)...")
        sent = 0
        while sent < len(image):
            chunk = image[sent:sent + CHUNK_SIZE]
            ser.write(chunk)
            ser.flush()
            sent += len(chunk)
            time.sleep(args.delay)

            if not wait_for_control(ser, CTRL_ACK, args.ack_timeout):
                print(f"[PC] stop at image {sent}/{len(image)} bytes")
                return

            print("[PC] got ACK")
            print(f"[PC] sent image {sent}/{len(image)} bytes")

        print("[PC] Send done. Listening for bootloader logs...")
        end_time = time.monotonic() + args.post_listen
        while time.monotonic() < end_time:
            if not drain_serial(ser):
                time.sleep(0.02)

        print("[PC] Done.")


if __name__ == "__main__":
    main()
